### ISSUE TITLE
Maintain this template for the Shaarli community fork

### ISSUE THREAD

**Issue by nodiscc** [kalvn/shaarli-blocks#3]
Hi @kalvn , Shaarli development is now active again on the community fork https://github.com/shaarli/Shaarli. You can read the README to know about the origins of the fork. We are willing to work on changes that will allow users to install third-party templates like yours directly via `git clone` or a simple unzip, without overwriting Shaarli's template. It will become easy to update Shaarli without overwrtigin your template, and vice-versa. It would be cool if you joined the discussion at https://github.com/shaarli/Shaarli/issues/163 or on https://gitter.im/shaarli/Shaarli to make your template compatible with this, and ensure it works with the latest fork. Then I could create a repository for your template at https://github.com/shaarli/ and give you write access so you can maintain it.

Interested?

**Comment by kalvn** [comment]
Yep, I joined the discussion. I'll update this thread when I finish working on this new version.
