### ISSUE TITLE
no suggestion for tags (do=addlink)

### ISSUE THREAD

**Issue by ParoTheParrot** [kalvn/shaarli-blocks#4]
in the "?post=" windows (new bookmark) the tag-suggestion does not work

**Comment by kalvn** [comment]
The theme hasn't been updated for a while, and the last version of Shaarli (0.0.45-beta) use a new way to display suggestions.
I will fix this in the next few days.

**Comment by ParoTheParrot** [comment]
is this fixed in the new 0.0.43 Version?

**Comment by kalvn** [comment]
No I just added a release tag to keep a version working for Shaarli 0.0.43-beta.
When it's fixed I will release a new version probably called 0.0.45-beta.

**Comment by kalvn** [comment]
The last release fixes this: https://github.com/kalvn/shaarli-blocks/releases/tag/v0.0.45-beta

**Comment by ParoTheParrot** [comment]
fixed, thanks!
