### ISSUE TITLE
Problem with Shaarli 0.5.1 

### ISSUE THREAD

**Issue by ParoTheParrot** [kalvn/shaarli-blocks#6]
After upgrading to the new shaarli I see this at every links-entray
Notice: Undefined index: localdate in /[MYSITEURL]/tmp/linklist.7f508c8754b9e69acc8387317c27d166.rtpl.php on line 93

PS: With your material TPL it look good!

**Comment by kalvn** [comment]
Yep it's normal, I didn't updated this theme to Shaarli 0.5.0 yet. Be careful when you update your version of Shaarli and be sure to check that your theme support it.
Concerning this one, it's written at the end of the homepage: 
> Shaarli Blocks was tested and validated on Shaarli 0.0.45 beta.

**Comment by ParoTheParrot** [comment]
Aha, ok. When will you update "blocks"?
I do like it more than the material theme

**Comment by kalvn** [comment]
I'll do it soon, I just need to find the time :)

**Comment by kalvn** [comment]
The last commit ( https://github.com/kalvn/shaarli-blocks/commit/26123f620670fef977dbab1070a95b5427c0d6fc ) should solve the issue.
Feel free to close the issue if it works for you.

**Comment by ParoTheParrot** [comment]
Very nice - thanks a lot! :+1:
