### ISSUE TITLE
Shaarli 0.6.0?

### ISSUE THREAD

**Issue by ParoTheParrot** [kalvn/shaarli-blocks#7]
Same question here: Everything adopted from https://github.com/shaarli/Shaarli/releases/tag/v0.6.0?
Can I use Shaarli-Material for Shaarli 0.6.0?

**Comment by ParoTheParrot** [comment]
... 0.6.1 is out!

**Comment by kalvn** [comment]
I'll try to find time to update this theme. Nevertheless, as I'm now working mainly on [Shaarli Material](https://github.com/kalvn/Shaarli-Material), I may give up updates for this theme in the future.

**Comment by ParoTheParrot** [comment]
..0.6.2!

**Comment by kalvn** [comment]
This theme is now officially abandoned. I'm sorry to make this decision but I don't have enough time to devote to it.
